FROM amazonlinux:2.0.20200602.0

RUN yum update -y && \
  yum install -y \
  amazon-linux-extras && \
  amazon-linux-extras enable python3.8 && \
  yum install -y python3.8 zip && \
  yum -y clean all

RUN python3.8 -m ensurepip

RUN python3.8 -m pip install --upgrade pip

RUN python3.8 -m pip install numpy==1.21.6